name: 'Slackify'
description: 'Slack Notification Action'
author: 'ilhamsyahids'

inputs:
  type:
    description: 'job status (success, failure or cancelled)'
    required: true
  job_name:
    description: 'title of the notification (format: markdown)'
    required: true
  mention:
    description: 'slack mention'
    required: false
  mention_if:
    description: 'the condition for mentioning'
    required: false
  username:
    description: 'legacy information slack username'
    required: false
  icon_emoji:
    description: 'legacy information slack icon emoji'
    required: false
  channel:
    description: 'legacy information slack channel'
    required: false
  url:
    description: 'slack incoming webhook url'
    required: false
  commit:
    description: 'whether include commit data or not (true or false)'
    required: false
    default: 'false'
  token:
    description: 'need to get commit data'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'bell'
  color: 'red'
