name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    env:
      TEST_TAG: localhost:5001/ilhamsyahids/slacktify:latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: Run the Container
        id: run
        run: |
          docker run \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_SHA=${{ github.sha }} \
            -e GITHUB_EVENT_NAME=${{ github.event_name }} \
            -e GITHUB_REF=${{ github.ref }} \
            -e GITHUB_WORKFLOW=${{ github.workflow }} \
            -e INPUT_TYPE=success 
            -e INPUT_JOB_NAME=Test \
            -e INPUT_MENTION=here \
            -e INPUT_MENTION_IF=failure \
            -e INPUT_URL="${{ secrets.SLACK_WEBHOOK_TEST }}" \
            -e INPUT_COMMIT=true \
            -e INPUT_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            --rm ${{ env.TEST_TAG }}

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          type: ${{ job.status }}
          job_name: ${{ github.job }}
          mention: here
          mention_if: failure
          url: ${{ secrets.SLACK_WEBHOOK_TEST }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.payload }}"
